[build]
  # This tells Netlify where to find your serverless functions
  functions = "netlify/functions"

# This is an optional but powerful rule. It makes your function accessible
# at a cleaner URL, like yoursite.com/api/get-live-results
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200