[build]
  functions = "netlify/functions"

# This increases the timeout for all functions to 26 seconds (the max on the free tier)
# This is the key to preventing the "displays nothing" error.
[functions]
  timeout = 26
